######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 15 12:58:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h qcustomplot.h
FORMS += mainWindow.ui
SOURCES += main.cpp mainWindow.cpp qcustomplot.cpp
