######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 16 11:45:27 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /usr/include/eigen3/

# Input
HEADERS += mainWindow.h qcustomplot.h ../binary.h ../ptMass.h
FORMS += mainWindow.ui
SOURCES += main.cpp mainWindow.cpp qcustomplot.cpp ../binary.cpp ../ptMass.cpp
